In [3]:
import pandas as pd
import matplotlib as plt 
import sklearn as sk
import glob
import os

In [28]:
path = '/Users/adiamtesfaselassie/Documents/Spring2023/ANLY521/JobPosts/data/'

jobs = glob.glob(path + "/*.csv")
df_list = (pd.read_csv(file) for file in jobs)
jobs_df = pd.concat(df_list)
jobs_df = jobs_df.dropna(subset=['Job'])
jobs_df
#df_jobs = pd.concat([pd.read_csv(f).set_index('A') for f in glob.glob('/Users/adiamtesfaselassie/Documents/Spring2023/ANLY521/JobPosts/Adiam/data')])

,Position Name,Job,Salary,Job Type,Shift & Schedule,Company,Location,Rating,URL,Id,...,geo,job_board,job_description,job_title,job_type,post_date,salary_offered,state,url,Job
0,Director of Women's Services,Healthcare Management,NaN,Full-time,NaN,Bolivar Medical Center,"Cleveland, MS 38732",3.8,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,7d46e088272f423d,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Health Services Director - Registered Nurse,Healthcare Management,NaN,Full-time,Monday to Friday,"Prestige Care, Inc.","Pendleton, OR 97801+10 locations",2.7,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,75134fbb214e21e8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Program Coordinator I,Healthcare Management,$17.83 - $30.33 an hour,Full-time,NaN,Coordinated Care,"Hybrid remote in Washington, DC+4 locations",3.2,https://www.indeed.com/rc/clk?jk=7a151ecfa759e...,7a151ecfa759eb7a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Director of Surgery,Healthcare Management,NaN,Full-time,Monday to Friday +1,Kindred Hospitals,"Rancho Cucamonga, CA 91730",3.3,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,ecab535cd6ff5437,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Operations Manager, Provider Success (Remote)",Healthcare Management,NaN,Full-time,NaN,Path Mental Health,"Remote in Los Angeles, CA",4.7,https://www.indeed.com/rc/clk?jk=5824c54186b26...,5824c54186b26f1d,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,Front End Software Engineer,Software Developer,NaN,Full-time,NaN,HP,"Spring, TX 77389",3.9,https://www.indeed.com/rc/clk?jk=97f8abed86ef0...,97f8abed86ef0d48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Software Developer I or II (Remote or Hybrid),Software Developer,NaN,Full-time,NaN,The Henry M. Jackson Foundation for the...,"Hybrid remote in Bethesda, MD 20817+1 location",3.7,https://www.indeed.com/rc/clk?jk=7864ac505fb39...,7864ac505fb398e2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,CAD Manager,Software Developer,NaN,Full-time,NaN,"Sanchez & Associates, P.C.","Chicago, IL 60656Â (Norwood Park area)",NaN,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,1246178cca27798c,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Lead Full Stack Developer,Software Developer,NaN,Full-time,NaN,T. Rowe Price,"Owings Mills, MD+3 locations",3.6,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,34fe8db3b5202875,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Entry level software developer,Software Developer,NaN,Full-time,NaN,Advance Solutions,United States,NaN,https://www.indeed.com/rc/clk?jk=e3b396b059ce8...,e3b396b059ce815f,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
discription_df = pd.DataFrame(zip(jobs_df['Short Description'], jobs_df['Job']), columns=['Discription', 'Job'])
discription_df.Job.unique()
discription_df

                                           Discription                     Job
0     \n Utilizes appropriate pain management techn...  Healthcare Management
1     \n Experience in geriatric nursing, medicatio...  Healthcare Management
2     \n Screen members by priority for case manage...  Healthcare Management
3    Kindred Hospital Rancho* is a 55 bed long-term...  Healthcare Management
4     \n Experience with high-growth startups, heal...  Healthcare Management
..                                                 ...                     ...
175   \n As a Software Engineering Apprentice at HP...     Software Developer
176  Subversion and/or other software version contr...     Software Developer
177   \n Working knowledge for processing LiDAR Poi...     Software Developer
178  We are seeking an experienced Lead Full Stack ...     Software Developer
179   \n Understands and can apply object-oriented ...     Software Developer

[180 rows x 2 columns]

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import TreebankWordTokenizer
from nltk.stem import PorterStemmer
import pandas as pd
import re
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF
from sklearn.metrics.pairwise import cosine_similarity

In [37]:
def tokenize_stem(series):
    
    tokenizer =TreebankWordTokenizer() 
    stemmer = PorterStemmer()
    series = series.apply(lambda x: tokenizer.tokenize(x))
    series = series.apply(lambda x: [stemmer.stem(w) for w in x])
    series = series.apply(lambda x: ' '.join(x))
    return series

In [38]:
def display_topics(model, feature_names, no_top_words, topic_names=None):
    for i, topic in enumerate(model.components_):
        if not topic_names or not topic_names[i]:
            print("\nTopic ", i)
        else:
            print("\nTopic: '",topic_names[i],"'")
        print(", ".join([feature_names[k]
                        for k in topic.argsort()[:-no_top_words - 1:-1]]))
    return [topic for topic in model.components_]
    return model.components_

In [41]:
def return_topics(series, num_topics, no_top_words, model, vectorizer):
    #turn job into series
    #df = jobs_df[jobs_df['Job']==job]
    
    
    #clean series
    
    series = tokenize_stem(series)
    #transform series into corpus
    ex_label = [e[:30]+"..." for e in series]
    #set vectorizer ngrams = (2,2)
    vec = vectorizer(stop_words = 'english')
    
    doc_word = vec.fit_transform(series)
    def_model = model(num_topics)
    doc_topic = def_model.fit_transform(doc_word)
    
    display_topics(def_model, vec.get_feature_names_out(), no_top_words)
    return def_model.components_, doc_topic#, topics

In [48]:
lsa = TruncatedSVD(2)
#array,doc = return_topics(discription_df['Discription'],1,2, NMF, TfidfVectorizer)
array,doc = return_topics(discription_df['Discription'],12, 30, NMF, TfidfVectorizer)
doc.shape

# look at topics and see what makes sense

# recommend roles that are best for you based on supervised learnings

# these are the jobs descriptions that are best for you based on your resume

# these are the best words for your resume based on which job you want to go into

Topic_DF = pd.DataFrame(doc)
Topic_DF.columns = ['Topic ' + str(i+1) for i in range(len(Topic_DF.columns)) ]

Topic  0
qualiti, assur, process, custom, compani, quality, manag, respons, procedures, provid, lead, profession, specialist, entri, ensur, control, analys, oversight, issu, initi, regular, organ, program, report, monitor, servic, champion, experience, experienc, level

Topic  1
data, engin, scientist, pipelin, design, collabor, build, solut, experi, integr, job, analyt, work, implement, requir, sourc, years, time, mdm, persist, model, standard, big, scienc, autom, processes, team, engineering, elect, engineer

Topic  2
financi, report, model, analysi, analyst, plan, prepar, skills, director, perform, provid, identifi, analyt, improv, financial, directli, account, monthli, strong, trend, respons, statement, review, experi, recommend, analyz, present, intern, modeling, budget

Topic  3
media, market, social, digit, email, includ, advertis, channel, campaign, search, blog, display, mobil, limit, brand, knowledg, content, strateg, manag, track, websit, creativ, partner, success, proven, record, et, tactic, al, ppc

Topic  4
softwar, develop, experi, work, design, support, applic, knowledg, software, compon, tool, databas, use, like, jira, confluence, prior, perform, addit, appli, industri, demonstr, solut, team, code, engin, offic, payment, solv, review

Topic  5
manag, year, role, experi, minimum, thi, care, account, center, instrument, successful, impact, preferred, coordin, prefer, directli, strong, project, candid, financ, requir, offic, plu, high, maintain, patient, experience, deliveri, qual, dn

Topic  6
busi, team, current, venture, embark, excit, sold, husband, wife, recent, partner, new, process, role, growth, technolog, bi, ma, boston, great, transform, bring, everi, hybrid, hire, intellig, key, remot, creativ, client

Topic  7
technic, abil, commun, individu, techn, sap, stakeholders, synthes, inform, non, busi, year, experi, skill, problem, solv, strong, knowledg, work, plan, content, white, paper, ebook, articl, conceiv, campaign, varieti, excel, suite

Topic  8
interact, manag, supplier, subordin, senior, custom, level, variou, peer, time, travel, team, 10, solv, abl, clearanc, trust, obtain, ye, mechan, work, problem, electr, hp, apprentic, larger, collabor, environ, serv, 2023

Topic  9
product, control, revis, environment, procedur, accuraci, rate, verifi, state, new, project, assist, perform, qualiti, day, influenc, offic, software, platform, support, ensur, everi, oper, curat, ltk, million, shopper, month, evalu, use

Topic  10
market, recommend, trend, activ, overal, engag, leader, oper, base, best, step, frequent, research, maintain, analyt, commun, aspect, innov, request, demand, tool, support, respons, identifi, skills, improv, day, analyst, strong, facil

Topic  11
polici, repres, audit, focus, matter, sit, subject, regulatori, expert, complianc, coordin, implement, peer, assur, qualiti, end, content, review, incumb, wid, agency, triennial, internal, knowledg, process, updat, score, demonstr, collabor, standard

/opt/anaconda3/envs/anly521/lib/python3.10/site-packages/sklearn/decomposition/_nmf.py:1665: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(

In [50]:
Topic_DF['job'] = discription_df.Job
Topic_DF.to_csv('topic_df.csv')
Topic_DF

,Topic 1,Topic 2,Topic 3,Topic 4,Topic 5,Topic 6,Topic 7,Topic 8,Topic 9,Topic 10,Topic 11,Topic 12,job
0,0.009893,0.000000,0.002483,0.001593,0.000000,0.088860,0.000000,0.000000,0.011107,0.000000,0.000000,0.000000,Healthcare Management
1,0.000000,0.000000,0.003045,0.003632,0.061334,0.210030,0.023372,0.000000,0.061277,0.000000,0.002863,0.000000,Healthcare Management
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.088831,0.000000,0.000000,0.028829,0.039346,0.090281,0.000000,Healthcare Management
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.075472,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Healthcare Management
4,0.000000,0.003291,0.000000,0.008555,0.005495,0.092667,0.004606,0.002490,0.000000,0.000000,0.003181,0.000000,Healthcare Management
...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,0.000000,0.074757,0.000000,0.000000,0.234257,0.000000,0.025058,0.000000,0.149915,0.000000,0.000000,0.000000,Software Developer
176,0.000000,0.000000,0.000000,0.000000,0.164478,0.023885,0.000000,0.000000,0.000000,0.165580,0.000000,0.000000,Software Developer
177,0.009995,0.000639,0.004871,0.006811,0.068944,0.002843,0.017647,0.009464,0.000000,0.042119,0.000000,0.001789,Software Developer
178,0.010675,0.000000,0.008784,0.032220,0.148733,0.135042,0.000000,0.020614,0.000000,0.000000,0.000000,0.000000,Software Developer
179,0.000000,0.000000,0.000000,0.000000,0.409801,0.000000,0.010945,0.000000,0.032536,0.014010,0.000000,0.000000,Software Developer